# Generated by Django 4.0.6 on 2022-07-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDatatable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=50, verbose_name='Organizaion name')),
                ('api_name', models.CharField(max_length=120, verbose_name='Api name')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('usages', models.IntegerField(verbose_name='Usages')),
            ],
        ),
    ]
